# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:

  build:
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for x86-64-linux
      run: GOOS=linux GOARCH=amd64 go build -v -o hostmodifier-x86-64-linux .

    - name: Build for arm-linux
      run: GOOS=linux GOARCH=arm go build -v -o hostmodifier-arm-linux .

    - name: Test
      run: go test -v .

    - name: Release binaries
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release
        upload-artifacts: true
